### ISSUE TITLE
Select Country From Dropdown

### ISSUE THREAD

**Issue by tragicmj** [fakeheal/react-native-intl-phone-field#3]
**Is your feature request related to a problem? Please describe.**
There should be a way to select country code from dropdown on basis of country
**Describe the solution you'd like**
There should be an option to select country from a dropdown and the country code gets updated on that basis. It would be great to have this feature.

**Comment by fakeheal** [comment]
Hi! 

First of all, thank you for considering this package. My entire idea behind creating it is to have something really lightweight, yet powerful, for formatting international phone numbers. This package is more suitable for adding phone input validation to "input-heavy" forms. Dropdowns or modals would only decrease the usability and probably distract the user from more important steps. 

For a library supporting country selection, please check this one out: [garganurag893/react-native-phone-number-input](https://github.com/garganurag893/react-native-phone-number-input).
