### ISSUE TITLE
automatic flag setting based on country code

### ISSUE THREAD

**Issue by bsrodrigue** [fakeheal/react-native-intl-phone-field#4]
Hello here! Thanks for building this, it helps, but I think there is still room for improvement.

I'd like to have a component that does not force me to google for flag emojis. It would be nice to have it automatically detect the appropriate flag by default and then let the user provide either a fallback flag or just a custom flag.

**Comment by fakeheal** [comment]
Hi, thanks for giving the library a go!

The library uses [`countries-list`](https://www.npmjs.com/package/countries-list) for getting the emojis of matched countries, so you don't have to provide/search the emojis yourself. And in the demo supplied in the repo (or [in this snack](https://snack.expo.dev/@itodorova/react-native-intl-phone-field-demo)), you can see the "Minimal" example requires no emojis to be passed to the component, but it still sets the flag if a valid phone number is entered.

Or am I missing something in your message?

**Comment by bsrodrigue** [comment]
My bad then, thanks for the reply
